name: mlflow_example
channels:
  - defaults

dependencies:
  - python=3.7
  - nb_conda
  - pip
  - pip:
    - numpy == 1.18.1
    - pandas == 1.0.5
    - tensorflow == 2.3.1
    - python-dotenv==0.14.0
    - pymysql
    - click
    - mlflow == 1.12.0
    - watermark == 2.0.2
